AuthOrder mod_auth_file.c mod_auth_unix.c
AuthUserFile /etc/proftpd/passwd
AuthGroupFile /etc/proftpd/groups
AuthAliasOnly off
AuthUsingAlias on
AllowEmptyPasswords off
RequireValidShell off
RootLogin off
DefaultRoot ~ ftp
DefaultChdir ~
MaxLoginAttempts 3
MaxPasswordSize 200
DeferWelcome on
UseFtpUsers on
PersistentPasswd on
AllowUser admin
AllowUser !guest
AllowGroup wheel
DenyGroup nogroup
DenyUser baduser
