DisplayConnect /etc/proftpd/welcome.msg
DisplayLogin /etc/proftpd/login.msg
DisplayChdir .message true
DisplayQuit goodbye.msg
DisplayFileTransfer transfer.msg
AccessGrantMsg "Welcome %u to %v"
AccessDenyMsg "Sorry, access denied"
ServerIdent off
